import {getSupabase} from './supabaseClient.js';
const c=()=>getSupabase(); const err=()=>new Error('Supabase is not configured.');
const mapContent=r=>r?({id:r.id,eyebrow:r.eyebrow||'',title:r.title||'',lead:r.lead||'',body:r.body||'',imageUrl:r.image_url||'',extraData:r.extra_data||{},updatedAt:r.updated_at}):null;
const mapService=r=>r?({id:r.id,title:r.title||'',description:r.description||'',imageUrl:r.image_url||'',displayOrder:r.display_order??0,createdAt:r.created_at,updatedAt:r.updated_at}):null;
const mapSocial=r=>r?({id:r.id,platform:r.platform||'',url:r.url||'',isActive:Boolean(r.is_active),displayOrder:r.display_order??0,updatedAt:r.updated_at}):null;
export async function getSiteContent(){const x=c();if(!x)return {data:null,error:err()};const {data,error}=await x.from('site_content').select('*').order('id');return {data:(data||[]).map(mapContent),error};}
export async function getSiteContentById(id){const x=c();if(!x)return {data:null,error:err()};const {data,error}=await x.from('site_content').select('*').eq('id',id).maybeSingle();return {data:mapContent(data),error};}
export async function updateSiteContent(id,d){const x=c();if(!x)return {data:null,error:err()};const p={};if(d.eyebrow!==undefined)p.eyebrow=d.eyebrow;if(d.title!==undefined)p.title=d.title;if(d.lead!==undefined)p.lead=d.lead;if(d.body!==undefined)p.body=d.body;if(d.imageUrl!==undefined)p.image_url=d.imageUrl;if(d.extraData!==undefined)p.extra_data=d.extraData;const {data,error}=await x.from('site_content').upsert({id,...p},{onConflict:'id'}).select().single();return {data:mapContent(data),error};}
export async function getCompanySettings(){const x=c();if(!x)return {data:null,error:err()};const {data,error}=await x.from('company_settings').select('*').eq('id','default').maybeSingle();return {data:data?{id:data.id,companyName:data.company_name,tagline:data.tagline,establishedYear:data.established_year,address:data.address,phone:data.phone,email:data.email,contactIntro:data.contact_intro,updatedAt:data.updated_at}:null,error};}
export async function updateCompanySettings(d){const x=c();if(!x)return {data:null,error:err()};const p={id:'default'};if(d.companyName!==undefined)p.company_name=d.companyName;if(d.tagline!==undefined)p.tagline=d.tagline;if(d.establishedYear!==undefined)p.established_year=d.establishedYear;if(d.address!==undefined)p.address=d.address;if(d.phone!==undefined)p.phone=d.phone;if(d.email!==undefined)p.email=d.email;if(d.contactIntro!==undefined)p.contact_intro=d.contactIntro;const {data,error}=await x.from('company_settings').upsert(p,{onConflict:'id'}).select().single();return {data:data?{id:data.id,companyName:data.company_name,tagline:data.tagline,establishedYear:data.established_year,address:data.address,phone:data.phone,email:data.email,contactIntro:data.contact_intro,updatedAt:data.updated_at}:null,error};}
export async function getServices(){const x=c();if(!x)return {data:null,error:err()};const {data,error}=await x.from('services').select('*').order('display_order').order('created_at');return {data:(data||[]).map(mapService),error};}
export async function createService(d){const x=c();if(!x)return {data:null,error:err()};const {data,error}=await x.from('services').insert({title:d.title,description:d.description||'',image_url:d.imageUrl||'',display_order:d.displayOrder??0}).select().single();return {data:mapService(data),error};}
export async function updateService(id,d){const x=c();if(!x)return {data:null,error:err()};const p={};if(d.title!==undefined)p.title=d.title;if(d.description!==undefined)p.description=d.description;if(d.imageUrl!==undefined)p.image_url=d.imageUrl;if(d.displayOrder!==undefined)p.display_order=d.displayOrder;const {data,error}=await x.from('services').update(p).eq('id',id).select().single();return {data:mapService(data),error};}
export async function deleteService(id){const x=c();if(!x)return {data:false,error:err()};const {data,error}=await x.from('services').delete().eq('id',id).select('id');if(error)return {data:false,error};if(!data?.length)return {data:false,error:new Error('Service was not deleted. It may not exist or your admin policy denied the operation.')};return {data:true,error:null};}
export async function getSocialLinks(includeInactive=true){const x=c();if(!x)return {data:null,error:err()};let q=x.from('social_links').select('*').order('display_order');if(!includeInactive)q=q.eq('is_active',true);const {data,error}=await q;return {data:(data||[]).map(mapSocial),error};}
export async function createSocialLink(d){const x=c();if(!x)return {data:null,error:err()};const {data,error}=await x.from('social_links').insert({platform:d.platform,url:d.url,is_active:d.isActive??true,display_order:d.displayOrder??0}).select().single();return {data:mapSocial(data),error};}
export async function updateSocialLink(id,d){const x=c();if(!x)return {data:null,error:err()};const p={};if(d.platform!==undefined)p.platform=d.platform;if(d.url!==undefined)p.url=d.url;if(d.isActive!==undefined)p.is_active=d.isActive;if(d.displayOrder!==undefined)p.display_order=d.displayOrder;const {data,error}=await x.from('social_links').update(p).eq('id',id).select().single();return {data:mapSocial(data),error};}
export async function deleteSocialLink(id){const x=c();if(!x)return {data:false,error:err()};const {data,error}=await x.from('social_links').delete().eq('id',id).select('id');if(error)return {data:false,error};if(!data?.length)return {data:false,error:new Error('Social link was not deleted. It may not exist or your admin policy denied the operation.')};return {data:true,error:null};}
