import {getSupabase} from './supabaseClient.js';
export const BUCKET_NAME='ecosafe-media';
export const VALID_FOLDERS=['projects','website','services','brand'];
export const ALLOWED_MIME_TYPES=['image/svg+xml','image/png','image/jpeg','image/webp'];
export const MAX_FILE_SIZE_BYTES=10*1024*1024;
const safe=(s)=>String(s||'file').toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'');
export function getPublicUrl(path){const c=getSupabase();if(!c||!path)return '';return c.storage.from(BUCKET_NAME).getPublicUrl(path).data.publicUrl;}
export function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
export async function uploadAsset(file,folder='website',usageTag=''){const c=getSupabase();if(!c)return {data:null,error:new Error('Supabase is not configured.')};if(!VALID_FOLDERS.includes(folder))return {data:null,error:new Error('Invalid media folder.')};if(!ALLOWED_MIME_TYPES.includes(file.type))return {data:null,error:new Error('Unsupported file type. Use SVG, PNG, JPG or WEBP.')};if(file.size>MAX_FILE_SIZE_BYTES)return {data:null,error:new Error('File exceeds the 10MB limit.')};const path=`${folder}/${Date.now()}-${safe(file.name)}`;const up=await c.storage.from(BUCKET_NAME).upload(path,file,{upsert:false,contentType:file.type,cacheControl:'3600'});if(up.error)return {data:null,error:up.error};const publicUrl=c.storage.from(BUCKET_NAME).getPublicUrl(path).data.publicUrl;const {data,error}=await c.from('media_assets').insert({filename:file.name,storage_path:path,public_url:publicUrl,usage_tag:usageTag,file_type:file.type.split('/')[1]?.toUpperCase()||'IMAGE',file_size:file.size}).select().single();if(error){await c.storage.from(BUCKET_NAME).remove([path]);return {data:null,error};}return {data,error:null};}
export async function deleteAsset(assetId,storagePath){const c=getSupabase();if(!c)return {data:false,error:new Error('Supabase is not configured.')};let path=storagePath; if(!path&&assetId){const q=await c.from('media_assets').select('storage_path').eq('id',assetId).maybeSingle();if(q.error)return {data:false,error:q.error};path=q.data?.storage_path||'';}if(path){const r=await c.storage.from(BUCKET_NAME).remove([path]);if(r.error)return {data:false,error:r.error};}if(assetId){const r=await c.from('media_assets').delete().eq('id',assetId).select('id');if(r.error)return {data:false,error:r.error};if(!r.data?.length)return {data:false,error:new Error('Media record was not deleted.')};}return {data:true,error:null};}
export async function listAssets(o={}){const c=getSupabase();if(!c)return {data:null,error:new Error('Supabase is not configured.')};let q=c.from('media_assets').select('*').order('created_at',{ascending:false});if(o.fileType&&o.fileType!=='All')q=q.eq('file_type',o.fileType);const {data,error}=await q;return {data:(data||[]).map(x=>({id:x.id,filename:x.filename,storagePath:x.storage_path,publicUrl:x.public_url,usageTag:x.usage_tag,fileType:x.file_type,fileSize:x.file_size,createdAt:x.created_at})),error};}
