import {getSupabase} from './supabaseClient.js';
const map=(r)=>r?({id:r.id,name:r.name||'',slug:r.slug||'',location:r.location||'',year:r.year||'',status:r.status||'Draft',description:r.description||'',featuredImage:r.featured_image||'',images:Array.isArray(r.images)?r.images:[],displayOrder:r.display_order??0,createdAt:r.created_at,updatedAt:r.updated_at}):null;
const payload=(d)=>{const p={}; for(const [k,v] of Object.entries({name:d.name,slug:d.slug,location:d.location,year:d.year,status:d.status,description:d.description,featured_image:d.featuredImage,images:Array.isArray(d.images)?d.images:undefined,display_order:d.displayOrder})){if(v!==undefined)p[k]=v;} if(!p.slug&&p.name)p.slug=String(p.name).toLowerCase().trim().replace(/[^\w\s-]/g,'').replace(/[\s_-]+/g,'-').replace(/^-+|-+$/g,''); return p;};
const required=()=>getSupabase()||null;
export async function getProjects(o={}){const c=required(); if(!c)return {data:null,error:new Error('Supabase is not configured.')}; let q=c.from('projects').select('*').order(o.orderBy==='updated'?'updated_at':'display_order',{ascending:o.ascending??(o.orderBy!=='updated')}); if(o.status&&o.status!=='All')q=q.eq('status',o.status); if(o.search){const s=String(o.search).replace(/[%_,]/g,''); q=q.or(`name.ilike.%${s}%,location.ilike.%${s}%`);} const {data,error}=await q; return {data:(data||[]).map(map),error};}
export async function getProject(id){const c=required(); if(!c)return {data:null,error:new Error('Supabase is not configured.')}; const {data,error}=await c.from('projects').select('*').eq('id',id).maybeSingle(); return {data:map(data),error};}
export async function getProjectBySlug(slug){const c=required(); if(!c)return {data:null,error:new Error('Supabase is not configured.')}; const {data,error}=await c.from('projects').select('*').eq('slug',slug).maybeSingle(); return {data:map(data),error};}
export async function createProject(d){const c=required(); if(!c)return {data:null,error:new Error('Supabase is not configured.')}; const {data,error}=await c.from('projects').insert(payload(d)).select().single(); return {data:map(data),error};}
export async function updateProject(id,d){const c=required(); if(!c)return {data:null,error:new Error('Supabase is not configured.')}; const {data,error}=await c.from('projects').update(payload(d)).eq('id',id).select().single(); return {data:map(data),error};}
export async function deleteProject(id){const c=required(); if(!c)return {data:false,error:new Error('Supabase is not configured.')}; const {data,error}=await c.from('projects').delete().eq('id',id).select('id'); if(error)return {data:false,error}; if(!data?.length)return {data:false,error:new Error('Project was not deleted. It may not exist or your admin policy denied the operation.')}; return {data:true,error:null};}
export async function reorderProjects(ids=[]){const c=required(); if(!c)return {data:false,error:new Error('Supabase is not configured.')}; for(let i=0;i<ids.length;i++){const {error}=await c.from('projects').update({display_order:i+1}).eq('id',ids[i]); if(error)return {data:false,error};} return {data:true,error:null};}
