import {
  isConfigured, signIn, signOut, getSession, getCurrentUser, checkAdminAuthorization, changePassword,
  getProjects, createProject, updateProject, deleteProject,
  getSiteContent, updateSiteContent, getCompanySettings, updateCompanySettings,
  getServices, createService, updateService, deleteService,
  getSocialLinks, createSocialLink, updateSocialLink, deleteSocialLink,
  listAssets, uploadAsset, deleteAsset,
  getEnquiries, getEnquiry, updateEnquiryStatus, deleteEnquiry
} from './services/index.js';

const state = { view:'dashboard', user:null, adminProfile:null, loading:false, data:{projects:[],services:[],siteContent:[],socialLinks:[],media:[],enquiries:[],settings:null} };
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = (v='') => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const getContent = (id, fallback={}) => state.data.siteContent.find(x=>x.id===id) || {id,...fallback,extraData:fallback.extraData||{}};
const toast = (message,type='ok') => { const r=$('#toast-root'); if(!r)return; r.innerHTML=`<div class="toast ${type}">${esc(message)}</div>`; setTimeout(()=>r.innerHTML='',3200); };
const modal = (html) => { const r=$('#modal-root'); r.innerHTML=html; };
const closeModal = () => { const r=$('#modal-root'); if(r) r.innerHTML=''; };

function loginView(error='') {
  document.body.innerHTML=`<div id="app"></div><div id="modal-root"></div><div id="toast-root"></div>`;
  $('#app').innerHTML=`<main class="login-page"><div class="login-card"><div class="login-brand"><img src="../assets/ecosafe-logo.png" alt="EcoSafe Bangladesh"><div><strong>EcoSafe Bangladesh</strong><span>CONTENT MANAGEMENT</span></div></div><div class="login-copy"><span class="eyebrow">Secure administrator access</span><h1>Manage EcoSafe with clarity.</h1><p>Update the public website content, initiatives, services, media and enquiries from one workspace.</p></div><form id="login-form" class="login-form"><label>Email<input id="login-email" type="email" autocomplete="username" placeholder="admin@ecosafebangladesh.org" required></label><label>Password<input id="login-password" type="password" autocomplete="current-password" placeholder="Enter your password" required></label>${error?`<div class="form-error">${esc(error)}</div>`:''}<button class="btn primary wide" type="submit">Sign in</button></form><div class="login-foot">EcoSafe Bangladesh · Admin</div></div></main>`;
  $('#login-form').onsubmit=async e=>{e.preventDefault();const btn=$('#login-form button');btn.disabled=true;btn.textContent='Signing in…';const {data,error}=await signIn($('#login-email').value.trim(),$('#login-password').value);if(error){loginView(error.message||'Unable to sign in.');return;}state.user=data.user;state.adminProfile=data.adminProfile;await boot();};
}

async function boot(){
  document.body.innerHTML='<div id="app"></div><div id="modal-root"></div><div id="toast-root"></div>';
  renderShell(); await loadData(); render();
}

async function loadData(){
  state.loading=true;
  const [p,s,c,sl,m,e,cs]=await Promise.all([getProjects(),getServices(),getSiteContent(),getSocialLinks(),listAssets(),getEnquiries(),getCompanySettings()]);
  state.data.projects=p.data||[]; state.data.services=s.data||[]; state.data.siteContent=c.data||[]; state.data.socialLinks=sl.data||[]; state.data.media=m.data||[]; state.data.enquiries=e.data||[]; state.data.settings=cs.data||null;
  state.loading=false;
}

function renderShell(){
  $('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand-row"><div class="brand-mark"><img src="../assets/ecosafe-logo.png" alt="EcoSafe"></div><div class="brand-copy"><strong>EcoSafe</strong><span>CONTENT STUDIO</span></div><button class="icon-btn mobile-close" data-action="close-sidebar">×</button></div><div class="sidebar-label">Manage</div><nav id="nav" class="nav">${navItem('dashboard','⌂','Dashboard')}${navItem('homepage','◈','Homepage')}${navItem('about','◌','About & Pilot')}${navItem('services','✦','Services')}${navItem('projects','▦','Projects & Initiatives')}${navItem('join','＋','Join Us')}${navItem('contact','↗','Contact & Social')}${navItem('media','▧','Media Library')}</nav><div class="sidebar-bottom">${navItem('settings','⚙','Settings')}<div class="profile-mini"><div class="avatar" id="avatar">AD</div><div><strong id="profile-name">EcoSafe Admin</strong><span id="profile-role">Administrator</span></div></div><button class="logout" id="logout">↪ Logout</button></div></aside><div class="sidebar-overlay" data-action="close-sidebar"></div><main class="main"><header class="topbar"><button class="icon-btn mobile-menu" data-action="open-sidebar">☰</button><div class="breadcrumb"><span>EcoSafe Bangladesh</span><i>/</i><strong id="crumb">Dashboard</strong></div><div class="top-actions"><button class="site-preview" data-action="preview">View website ↗</button><div class="top-avatar" id="top-avatar">AD</div></div></header><section id="view-root" class="content"></section></main></div>`;
  const email=state.user?.email||'admin@ecosafebangladesh.org'; const initials=email.slice(0,2).toUpperCase(); $('#avatar').textContent=initials; $('#top-avatar').textContent=initials; $('#profile-name').textContent=email.split('@')[0]; $('#profile-role').textContent=state.adminProfile?.role||'Administrator';
  $('#nav').onclick=e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;render();closeSidebar();};
  $('#logout').onclick=async()=>{await signOut();state.user=null;state.adminProfile=null;loginView();};
  document.addEventListener('click',globalClick,{once:true});
}
function navItem(id,icon,label){return `<button class="nav-item ${state.view===id?'active':''}" data-view="${id}"><span class="nav-icon">${icon}</span><span>${label}</span>${id==='projects'?`<span class="nav-count">${state.data.projects.length}</span>`:''}</button>`;}
function globalClick(e){
  const action=e.target.closest('[data-action]'); if(action){if(action.dataset.action==='preview')window.open('../index.html','_blank');if(action.dataset.action==='open-sidebar')document.querySelector('.sidebar')?.classList.add('open');if(action.dataset.action==='close-sidebar')closeSidebar();}
  if(e.target.closest('[data-close-modal]')) closeModal();
  document.addEventListener('click',globalClick,{once:true});
}
function closeSidebar(){document.querySelector('.sidebar')?.classList.remove('open');}

function header(title,desc,action=''){return `<div class="view-head"><div><span class="eyebrow">EcoSafe Content Studio</span><h1>${esc(title)}</h1><p>${esc(desc||'')}</p></div>${action}</div>`;}
function panel(title,body,meta=''){return `<section class="panel"><div class="panel-head"><div class="panel-title">${esc(title)}</div>${meta?`<span class="panel-meta">${esc(meta)}</span>`:''}</div>${body}</section>`;}
function card(title,desc,button,id){return `<article class="content-card"><div><span class="eyebrow">Editable section</span><h3>${esc(title)}</h3><p>${esc(desc)}</p></div><button class="btn small" data-edit-content="${esc(id)}">${esc(button||'Edit')}</button></article>`;}
function field(label,id,value='',opts={}){const type=opts.type||'text'; if(type==='textarea')return `<label class="field"><span>${esc(label)}</span><textarea id="${id}" placeholder="${esc(opts.placeholder||'')}" ${opts.rows?`rows="${opts.rows}"`:''}>${esc(value)}</textarea></label>`;return `<label class="field"><span>${esc(label)}</span><input id="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(opts.placeholder||'')}"></label>`;}
function lines(value=[]){return Array.isArray(value)?value.join('\n'):'';}

function render(){
  $('#crumb').textContent={dashboard:'Dashboard',homepage:'Homepage',about:'About & Pilot',services:'Services',projects:'Projects & Initiatives',join:'Join Us',contact:'Contact & Social',media:'Media Library',settings:'Settings'}[state.view]||'Dashboard';
  $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));
  const views={dashboard:renderDashboard,homepage:renderHomepage,about:renderAbout,services:renderServices,projects:renderProjects,join:renderJoin,contact:renderContact,media:renderMedia,settings:renderSettings}; $('#view-root').innerHTML=(views[state.view]||renderDashboard)(); attachViewEvents();
}

function renderDashboard(){const c=state.data.siteContent;return header('Dashboard','A focused workspace for the EcoSafe public website.')+`<div class="stats-grid"><div class="stat"><span>Published initiatives</span><strong>${state.data.projects.filter(x=>x.status!=='Draft').length}</strong></div><div class="stat"><span>Core services</span><strong>${state.data.services.length}</strong></div><div class="stat"><span>Media assets</span><strong>${state.data.media.length}</strong></div><div class="stat"><span>New enquiries</span><strong>${state.data.enquiries.filter(x=>x.status==='New').length}</strong></div></div><div class="grid two"><div>${panel('Content status',`<div class="status-list"><div><span>Homepage</span><b>Editable</b></div><div><span>About & pilot</span><b>Editable</b></div><div><span>Services</span><b>${state.data.services.length} records</b></div><div><span>Projects & initiatives</span><b>${state.data.projects.length} records</b></div><div><span>Join Us</span><b>Editable</b></div><div><span>Contact & Social</span><b>Editable</b></div></div>`)}</div><div>${panel('Quick actions',`<div class="quick-actions"><button class="quick" data-view-jump="projects">+ Add initiative</button><button class="quick" data-view-jump="services">+ Add service</button><button class="quick" data-view-jump="media">Upload media</button><button class="quick" data-view-jump="contact">Review enquiries</button></div>`)}</div></div><div class="grid two"><div>${panel('Recent initiatives',state.data.projects.slice(0,5).map(p=>`<div class="list-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.status)} · ${esc(p.location)}</small></div><button class="row-action" data-edit-project="${p.id}">Edit</button></div>`).join('')||'<div class="empty">No initiatives yet.</div>')}</div><div>${panel('Latest enquiries',state.data.enquiries.slice(0,5).map(e=>`<div class="list-row"><div><strong>${esc(e.name)}</strong><small>${esc(e.email)} · ${esc(e.status)}</small></div><button class="row-action" data-view-enquiry="${e.id}">View</button></div>`).join('')||'<div class="empty">No enquiries yet.</div>')}</div></div>`;}

function renderHomepage(){const c=getContentMap();const s1=c.homepage_story_1||{};const s2=c.homepage_story_2||{};const s3=c.homepage_story_3||{};const focus=c.homepage_focus||{};const mission=c.homepage_mission||{};const programs=c.homepage_programs||{};const cta=c.homepage_cta||{};const items=focus.extraData?.items||[];return header('Homepage','Edit the exact text used by the live homepage. Images remain fixed unless you change them in the Media Library.')+`<div class="editor-stack">${contentEditorCard('Opening story',s1,'homepage_story_1','Edit story')}${contentEditorCard('Purpose story',s2,'homepage_story_2','Edit story')}${contentEditorCard('Vision story',s3,'homepage_story_3','Edit story')}${contentEditorCard('Areas of focus',focus,'homepage_focus','Edit focus')}${contentEditorCard('Mission & vision',mission,'homepage_mission','Edit mission')}${contentEditorCard('Programs & initiatives',programs,'homepage_programs','Edit section')}${contentEditorCard('Get involved CTA',cta,'homepage_cta','Edit CTA')}</div>`;}
function renderAbout(){const ids=['about_hero','about_feature','about_intro','about_problem','about_pilot','about_outcomes','about_other_programs','about_longterm'];const labels={about_hero:'Page hero',about_feature:'Featured waste-management pilot',about_intro:'About the project',about_problem:'Problem statement',about_pilot:'Pilot brief',about_outcomes:'Expected outcomes',about_other_programs:'Other programs & initiatives',about_longterm:'Long-term direction'};return header('About & Pilot','Manage the About / Programs page. The client-supplied waste-management pilot copy is stored here as editable content.')+`<div class="editor-stack">${ids.map(id=>{const c=getContentMap()[id]||{id};return contentEditorCard(labels[id],c,id,'Edit section');}).join('')}</div>`;}
function renderJoin(){const ids=['join_intro','join_volunteer','join_collaborate','join_research','join_partner','join_cta'];const labels={join_intro:'Join Us hero',join_volunteer:'Volunteer',join_collaborate:'Collaborate',join_research:'Research',join_partner:'Partner',join_cta:'Closing CTA'};return header('Join Us','Edit volunteer, collaboration, research and partnership messaging.')+`<div class="editor-stack">${ids.map(id=>{const c=getContentMap()[id]||{id};return contentEditorCard(labels[id],c,id,'Edit');}).join('')}</div>`;}
function renderContentPreview(c){return [c.eyebrow,c.title,c.lead,c.body].filter(Boolean).join(' — ');}
function contentEditorCard(label,c,id,button){let desc=renderContentPreview(c);if(id==='homepage_focus')desc=`${c.lead||''} · ${(c.extraData?.items||[]).length} focus areas`;if(id==='homepage_mission')desc=`${c.title||''} · mission + vision`;if(id==='about_outcomes')desc=`${(c.extraData?.items||[]).length} expected outcomes`;if(id==='about_longterm'||id==='projects_longterm')desc=`${(c.extraData?.items||[]).length} long-term directions`;return `<article class="editor-card"><div><span class="eyebrow">${esc(label)}</span><h2>${esc(c.title||c.eyebrow||label)}</h2><p>${esc(desc)}</p></div><button class="btn small" data-edit-content="${esc(id)}">${esc(button)}</button></article>`;}
function getContentMap(){return Object.fromEntries(state.data.siteContent.map(x=>[x.id,x]));}

function renderServices(){return header('Services','Manage the ten EcoSafe core service areas shown on the public website.','<button class="btn primary" data-add-service>Add service</button>')+`<div class="table-panel"><div class="table-wrap"><table class="table"><thead><tr><th>Service</th><th>Description</th><th>Order</th><th>Actions</th></tr></thead><tbody>${state.data.services.map(s=>`<tr><td><strong>${esc(s.title)}</strong></td><td>${esc(s.description)}</td><td>${s.displayOrder}</td><td><div class="row-actions"><button class="row-action" data-edit-service="${s.id}">Edit</button><button class="row-action danger-text" data-delete-service="${s.id}">Delete</button></div></td></tr>`).join('')||`<tr><td colspan="4"><div class="empty">No services yet.</div></td></tr>`}</tbody></table></div></div>`;}
function renderProjects(){return header('Projects & Initiatives','Manage the project/program cards used across the homepage, About page and Projects page.','<button class="btn primary" data-add-project>Add initiative</button>')+`<div class="toolbar"><input id="project-search" placeholder="Search initiatives…"><select id="project-status"><option>All</option><option>Published</option><option>Ongoing</option><option>Completed</option><option>Upcoming</option><option>Draft</option></select></div><div class="project-admin-grid">${state.data.projects.map(p=>`<article class="project-admin-card"><img src="${esc(p.featuredImage||'../assets/ecosafe-logo.png')}" alt=""><div class="project-admin-copy"><span class="eyebrow">${esc(p.status)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><small>${esc(p.location)} ${p.year?'· '+esc(p.year):''}</small><div class="row-actions"><button class="row-action" data-edit-project="${p.id}">Edit</button><button class="row-action danger-text" data-delete-project="${p.id}">Delete</button></div></div></article>`).join('')||'<div class="empty">No initiatives yet.</div>'}</div>`;}
function renderContact(){
  const s=state.data.settings||{};
  const contactForm = `<form id="contact-form" class="form-grid">${field('Organization name','set-name',s.companyName||'EcoSafe Bangladesh')}${field('Tagline','set-tagline',s.tagline||'Greener. Healthier. More Inclusive.')}${field('Address','set-address',s.address||'Banani DOHS, Dhaka, Bangladesh')}${field('Phone','set-phone',s.phone||'')}${field('Email','set-email',s.email||'')}${field('Contact intro','set-intro',s.contactIntro||'For partnerships, research, consultancy and community initiatives.',{type:'textarea',rows:4})}<button class="btn primary" type="submit">Save contact details</button></form>`;
  const socialHtml = `<div class="social-list">${state.data.socialLinks.map(x=>`<div class="social-row"><div><strong>${esc(x.platform)}</strong><a href="${esc(x.url)}" target="_blank" rel="noreferrer">${esc(x.url)}</a></div><div class="row-actions"><button class="row-action" data-edit-social="${x.id}">Edit</button><button class="row-action danger-text" data-delete-social="${x.id}">Delete</button></div></div>`).join('')||'<div class="empty">No social links added yet.</div>'}</div><button class="btn" data-add-social style="margin-top:14px">Add social link</button>`;
  const enquiriesHtml = `<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Contact</th><th>Message</th><th>Status</th><th>Actions</th></tr></thead><tbody>${state.data.enquiries.map(e=>`<tr><td><strong>${esc(e.name)}</strong></td><td>${esc(e.email)}<br><small>${esc(e.phone||'No phone')}</small></td><td>${esc(e.message)}</td><td><span class="status ${e.status.toLowerCase()}">${esc(e.status)}</span></td><td><div class="row-actions"><button class="row-action" data-view-enquiry="${e.id}">View</button><button class="row-action danger-text" data-delete-enquiry="${e.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">No enquiries yet.</div></td></tr>'}</tbody></table></div>`;
  return header('Contact & Social','Manage public contact details, social links and incoming enquiries.') + `<div class="grid two"><div>${panel('Public contact details',contactForm)}</div><div>${panel('Social links',socialHtml)}</div></div>${panel('Contact enquiries',enquiriesHtml)}`;
}
function renderMedia(){return header('Media Library','Upload and manage reusable website images in EcoSafe Storage.','<button class="btn primary" data-upload-media>Upload image</button>')+`<div class="media-grid">${state.data.media.map(m=>`<article class="media-card"><img src="${esc(m.publicUrl)}" alt=""><div><strong>${esc(m.filename)}</strong><small>${esc(m.usageTag||'General')} · ${Math.round((m.fileSize||0)/1024)} KB</small><div class="row-actions"><button class="row-action danger-text" data-delete-media="${m.id}" data-storage-path="${esc(m.storagePath)}">Delete</button></div></div></article>`).join('')||'<div class="empty">No uploaded media yet.</div>'}</div>`;}
function renderSettings(){return header('Settings','Account and workspace settings.')+`<div class="grid two"><div>${panel('Admin account',`<div class="settings-block"><div><span class="eyebrow">Signed in as</span><strong>${esc(state.user?.email||'')}</strong></div><div><span class="eyebrow">Role</span><strong>${esc(state.adminProfile?.role||'admin')}</strong></div></div>`)}</div><div>${panel('Change password',`<form id="password-form" class="form-grid">${field('Current password','current-pass','',{type:'password'})}${field('New password','new-pass','',{type:'password'})}${field('Confirm new password','confirm-pass','',{type:'password'})}<button class="btn primary" type="submit">Update password</button></form>`)}</div></div>`;}

function attachViewEvents(){
  $$('[data-view-jump]').forEach(b=>b.onclick=()=>{state.view=b.dataset.viewJump;render();});
  $$('[data-edit-content]').forEach(b=>b.onclick=()=>openContentEditor(b.dataset.editContent));
  $$('[data-add-project]').forEach(b=>b.onclick=()=>projectModal()); $$('[data-edit-project]').forEach(b=>b.onclick=()=>projectModal(state.data.projects.find(x=>x.id===b.dataset.editProject)));
  $$('[data-delete-project]').forEach(b=>b.onclick=()=>confirmDelete('Delete this initiative?','This removes the initiative from the CMS and public listings.',async()=>{const r=await deleteProject(b.dataset.deleteProject);if(r.error)throw r.error;await loadData();render();toast('Initiative deleted.');}));
  $$('[data-add-service]').forEach(b=>b.onclick=()=>serviceModal()); $$('[data-edit-service]').forEach(b=>b.onclick=()=>serviceModal(state.data.services.find(x=>x.id===b.dataset.editService)));
  $$('[data-delete-service]').forEach(b=>b.onclick=()=>confirmDelete('Delete this service?','This removes the service from the CMS.',async()=>{const r=await deleteService(b.dataset.deleteService);if(r.error)throw r.error;await loadData();render();toast('Service deleted.');}));
  $$('[data-add-social]').forEach(b=>b.onclick=()=>socialModal()); $$('[data-edit-social]').forEach(b=>b.onclick=()=>socialModal(state.data.socialLinks.find(x=>x.id===b.dataset.editSocial)));
  $$('[data-delete-social]').forEach(b=>b.onclick=()=>confirmDelete('Delete this social link?','This removes the link from the public social list.',async()=>{const r=await deleteSocialLink(b.dataset.deleteSocial);if(r.error)throw r.error;await loadData();render();toast('Social link deleted.');}));
  $$('[data-delete-media]').forEach(b=>b.onclick=()=>confirmDelete('Delete this media file?','The Storage object and its database record will both be removed.',async()=>{const r=await deleteAsset(b.dataset.deleteMedia,b.dataset.storagePath);if(r.error)throw r.error;await loadData();render();toast('Media deleted.');}));
  $$('[data-view-enquiry]').forEach(b=>b.onclick=()=>enquiryModal(b.dataset.viewEnquiry)); $$('[data-delete-enquiry]').forEach(b=>b.onclick=()=>confirmDelete('Delete this enquiry?','This permanently removes the enquiry from the inbox.',async()=>{const r=await deleteEnquiry(b.dataset.deleteEnquiry);if(r.error)throw r.error;await loadData();render();toast('Enquiry deleted.');}));
  const cf=$('#contact-form');if(cf)cf.onsubmit=async e=>{e.preventDefault();const r=await updateCompanySettings({companyName:$('#set-name').value.trim(),tagline:$('#set-tagline').value.trim(),address:$('#set-address').value.trim(),phone:$('#set-phone').value.trim(),email:$('#set-email').value.trim(),contactIntro:$('#set-intro').value.trim()});if(r.error){toast(r.error.message,'error');return;}await loadData();toast('Contact details saved.');};
  const pf=$('#password-form');if(pf)pf.onsubmit=async e=>{e.preventDefault();if($('#new-pass').value!==$('#confirm-pass').value){toast('New passwords do not match.','error');return;}const r=await changePassword($('#current-pass').value,$('#new-pass').value);if(r.error){toast(r.error.message,'error');return;}pf.reset();toast('Password updated.');};
  const ps=$('#project-search');if(ps)ps.oninput=()=>filterProjects(); const st=$('#project-status');if(st)st.onchange=()=>filterProjects();
  const up=$('[data-upload-media]');if(up)up.onclick=()=>uploadMedia();
}
function filterProjects(){const q=($('#project-search')?.value||'').toLowerCase();const status=$('#project-status')?.value||'All';$$('.project-admin-card').forEach(card=>{const text=card.textContent.toLowerCase();card.style.display=(!q||text.includes(q))&&(!status||status==='All'||text.includes(status.toLowerCase()))?'':'none';});}
function confirmDelete(title,message,fn){modal(`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow danger-label">Confirm</span><h2>${esc(title)}</h2></div><button class="icon-btn" data-close-modal>×</button></div><div class="modal-body"><p>${esc(message)}</p></div><div class="modal-foot"><button class="btn" data-close-modal>Cancel</button><button class="btn danger" id="confirm-delete">Delete</button></div></div></div>`);$('#confirm-delete').onclick=async()=>{const b=$('#confirm-delete');b.disabled=true;b.textContent='Deleting…';try{await fn();closeModal();}catch(e){toast(e.message||'Delete failed.','error');b.disabled=false;b.textContent='Delete';}};}

function openContentEditor(id){
  const c=getContentMap()[id]||{id,eyebrow:'',title:'',lead:'',body:'',extraData:{}}; let body='';
  if(id==='homepage_focus') body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Intro text','ce-lead',c.lead,{type:'textarea',rows:4})+field('Focus areas — one per line as Title | Description','ce-items',lines((c.extraData?.items||[]).map(x=>`${x.title} | ${x.description}`)),{type:'textarea',rows:12});
  else if(id==='homepage_mission') body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Heading','ce-title',c.title,{type:'textarea',rows:2})+field('Mission','ce-mission',c.extraData?.mission||'',{type:'textarea',rows:5})+field('Vision','ce-vision',c.extraData?.vision||'',{type:'textarea',rows:5});
  else if(id==='about_intro') body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Heading','ce-title',c.title,{type:'textarea',rows:2})+field('Paragraph 1','ce-p1',c.extraData?.paragraph1||'',{type:'textarea',rows:7})+field('Paragraph 2','ce-p2',c.extraData?.paragraph2||'',{type:'textarea',rows:5});
  else if(id==='about_problem') body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Heading','ce-title',c.title)+field('Problem paragraph 1','ce-p1',c.extraData?.paragraph1||'',{type:'textarea',rows:6})+field('Problem paragraph 2','ce-p2',c.extraData?.paragraph2||'',{type:'textarea',rows:5})+field('Waste-to-energy context','ce-p3',c.extraData?.paragraph3||'',{type:'textarea',rows:6});
  else if(id==='about_outcomes') body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Outcomes — one per line','ce-items',lines(c.extraData?.items||[]),{type:'textarea',rows:10});
  else if(id==='homepage_programs') body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Intro paragraph','ce-lead',c.lead||'',{type:'textarea',rows:5})+field('Selected initiative IDs — comma separated','ce-selected',(c.extraData?.selectedProjectIds||[]).join(','))+`<p class="field-help">Use the IDs shown in the Projects & Initiatives list. Leave empty to show the first two published initiatives.</p>`;
  else if(id==='about_longterm'||id==='projects_longterm') body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Directions — one JSON object per line','ce-items',lines((c.extraData?.items||[]).map(x=>JSON.stringify({eyebrow:x.eyebrow,title:x.title,description:x.description,image:x.image}))),{type:'textarea',rows:12,placeholder:'{"eyebrow":"…","title":"…","description":"…","image":"https://…"}'});
  else if(id==='about_other_programs') body=field('Selected project IDs — comma separated','ce-selected',(c.extraData?.selectedProjectIds||[]).join(','))+`<p class="field-help">Use the IDs shown in the Projects page editor. Leave empty to show the first three published initiatives.</p>`;
  else body=field('Eyebrow','ce-eyebrow',c.eyebrow)+field('Heading','ce-title',c.title,{type:'textarea',rows:3})+field('Lead / main paragraph','ce-lead',c.lead||'',{type:'textarea',rows:6})+field('Body','ce-body',c.body||'',{type:'textarea',rows:6});
  modal(`<div class="modal-backdrop"><div class="modal modal-wide"><div class="modal-head"><div><span class="eyebrow">EcoSafe section editor</span><h2>Edit ${esc(id.replaceAll('_',' '))}</h2></div><button class="icon-btn" data-close-modal>×</button></div><form id="content-form"><div class="modal-body form-grid">${body}</div><div class="modal-foot"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn primary" type="submit">Save changes</button></div></form></div></div>`);
  $('#content-form').onsubmit=async e=>{e.preventDefault();const payload={eyebrow:$('#ce-eyebrow')?.value.trim(),title:$('#ce-title')?.value.trim(),lead:$('#ce-lead')?.value.trim(),body:$('#ce-body')?.value.trim(),extraData:{...(c.extraData||{})}};
    if(id==='homepage_focus')payload.extraData.items=$('#ce-items').value.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [a,...b]=x.split('|');return {title:a.trim(),description:b.join('|').trim()};});
    if(id==='homepage_mission')payload.extraData={...(c.extraData||{}),mission:$('#ce-mission').value.trim(),vision:$('#ce-vision').value.trim()};
    if(id==='about_intro')payload.extraData={...(c.extraData||{}),paragraph1:$('#ce-p1').value.trim(),paragraph2:$('#ce-p2').value.trim()};
    if(id==='about_problem')payload.extraData={...(c.extraData||{}),paragraph1:$('#ce-p1').value.trim(),paragraph2:$('#ce-p2').value.trim(),paragraph3:$('#ce-p3').value.trim()};
    if(id==='about_outcomes')payload.extraData={...(c.extraData||{}),items:$('#ce-items').value.split(/\n+/).map(x=>x.trim()).filter(Boolean)};
    if(id==='homepage_programs')payload.extraData={...(c.extraData||{}),selectedProjectIds:$('#ce-selected').value.split(',').map(x=>x.trim()).filter(Boolean)};
    if(id==='about_longterm'||id==='projects_longterm'){try{payload.extraData={...(c.extraData||{}),items:$('#ce-items').value.split(/\n+/).map(x=>JSON.parse(x.trim())).filter(Boolean)};}catch(err){toast('Long-term direction JSON has an error.','error');return;}}
    if(id==='about_other_programs')payload.extraData={...(c.extraData||{}),selectedProjectIds:$('#ce-selected').value.split(',').map(x=>x.trim()).filter(Boolean)};
    const r=await updateSiteContent(id,payload);if(r.error){toast(r.error.message,'error');return;}await loadData();closeModal();render();toast('Section saved.');
  };
}

function projectModal(p=null){const edit=!!p;const x=p||{name:'',location:'Bangladesh',year:'',status:'Published',description:'',featuredImage:'',images:[]};modal(`<div class="modal-backdrop"><div class="modal modal-wide"><div class="modal-head"><div><span class="eyebrow">Projects & initiatives</span><h2>${edit?'Edit initiative':'Add initiative'}</h2></div><button class="icon-btn" data-close-modal>×</button></div><form id="project-form"><div class="modal-body form-grid">${field('Name','pr-name',x.name)}${field('Location','pr-location',x.location)}${field('Year','pr-year',x.year)}<label class="field"><span>Status</span><select id="pr-status"><option ${x.status==='Published'?'selected':''}>Published</option><option ${x.status==='Ongoing'?'selected':''}>Ongoing</option><option ${x.status==='Completed'?'selected':''}>Completed</option><option ${x.status==='Upcoming'?'selected':''}>Upcoming</option><option ${x.status==='Draft'?'selected':''}>Draft</option></select></label>${field('Description','pr-description',x.description,{type:'textarea',rows:5})}${field('Featured image URL','pr-image',x.featuredImage||'',{placeholder:'Upload via Media Library or paste a public image URL'})}</div><div class="modal-foot"><button class="btn" type="button" data-close-modal>Cancel</button><button class="btn primary" type="submit">${edit?'Save initiative':'Create initiative'}</button></div></form></div></div>`);$('#project-form').onsubmit=async e=>{e.preventDefault();const payload={name:$('#pr-name').value.trim(),location:$('#pr-location').value.trim(),year:$('#pr-year').value.trim(),status:$('#pr-status').value,description:$('#pr-description').value.trim(),featuredImage:$('#pr-image').value.trim(),images:x.images||[]};const r=edit?await updateProject(x.id,payload):await createProject(payload);if(r.error){toast(r.error.message,'error');return;}await loadData();closeModal();render();toast(edit?'Initiative updated.':'Initiative created.');};}
function serviceModal(s=null){const edit=!!s;const x=s||{title:'',description:'',displayOrder:state.data.services.length+1,imageUrl:''};modal(`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow">Services</span><h2>${edit?'Edit service':'Add service'}</h2></div><button class="icon-btn" data-close-modal>×</button></div><form id="service-form"><div class="modal-body form-grid">${field('Service title','sv-title',x.title)}${field('Display order','sv-order',x.displayOrder,{type:'number'})}${field('Description','sv-description',x.description,{type:'textarea',rows:7})}</div><div class="modal-foot"><button class="btn" type="button" data-close-modal>Cancel</button><button class="btn primary" type="submit">Save service</button></div></form></div></div>`);$('#service-form').onsubmit=async e=>{e.preventDefault();const payload={title:$('#sv-title').value.trim(),description:$('#sv-description').value.trim(),displayOrder:Number($('#sv-order').value)||0,imageUrl:x.imageUrl||''};const r=edit?await updateService(x.id,payload):await createService(payload);if(r.error){toast(r.error.message,'error');return;}await loadData();closeModal();render();toast('Service saved.');};}
function socialModal(s=null){const edit=!!s;const x=s||{platform:'Facebook',url:'',isActive:true,displayOrder:state.data.socialLinks.length+1};modal(`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow">Social presence</span><h2>${edit?'Edit social link':'Add social link'}</h2></div><button class="icon-btn" data-close-modal>×</button></div><form id="social-form"><div class="modal-body form-grid">${field('Platform','so-platform',x.platform)}${field('URL','so-url',x.url,{type:'url',placeholder:'https://…'})}${field('Display order','so-order',x.displayOrder,{type:'number'})}</div><div class="modal-foot"><button class="btn" type="button" data-close-modal>Cancel</button><button class="btn primary" type="submit">Save link</button></div></form></div></div>`);$('#social-form').onsubmit=async e=>{e.preventDefault();const payload={platform:$('#so-platform').value.trim(),url:$('#so-url').value.trim(),displayOrder:Number($('#so-order').value)||0,isActive:true};const r=edit?await updateSocialLink(x.id,payload):await createSocialLink(payload);if(r.error){toast(r.error.message,'error');return;}await loadData();closeModal();render();toast('Social link saved.');};}
async function enquiryModal(id){const r=await getEnquiry(id);if(r.error){toast(r.error.message,'error');return;}const e=r.data;modal(`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow">Contact enquiry</span><h2>${esc(e.name)}</h2></div><button class="icon-btn" data-close-modal>×</button></div><div class="modal-body enquiry-detail"><p><strong>Email:</strong> ${esc(e.email)}</p><p><strong>Phone:</strong> ${esc(e.phone||'—')}</p><p><strong>Organization:</strong> ${esc(e.organization||'—')}</p><p><strong>Message:</strong><br>${esc(e.message)}</p><label class="field"><span>Status</span><select id="enq-status"><option ${e.status==='New'?'selected':''}>New</option><option ${e.status==='Read'?'selected':''}>Read</option><option ${e.status==='Archived'?'selected':''}>Archived</option></select></label></div><div class="modal-foot"><button class="btn" data-close-modal>Close</button><button class="btn primary" id="save-enq">Save status</button></div></div></div>`);$('#save-enq').onclick=async()=>{const q=await updateEnquiryStatus(id,$('#enq-status').value);if(q.error){toast(q.error.message,'error');return;}await loadData();closeModal();render();toast('Enquiry status updated.');};}
async function uploadMedia(){const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/svg+xml';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const r=await uploadAsset(file,'website','Website image');if(r.error){toast(r.error.message,'error');return;}await loadData();render();toast('Image uploaded.');};input.click();}

(async()=>{if(!isConfigured()){loginView('Supabase is not configured in js/supabase-config.js.');return;}const s=await getSession();if(s.data?.user){const u=await getCurrentUser();const a=await checkAdminAuthorization(u.data?.id);if(!a.error&&a.data){state.user=u.data;state.adminProfile=a.data;await boot();return;}}loginView();})();
